//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phones
    {
        public int idPhone { get; set; }
        public string phone_Number { get; set; }
        public string company { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<bool> assign { get; set; }
    }
}
